name: Pull Request Workflow
on:
  pull_request:
    types:
      - opened
      - reopened
      - ready_for_review

    branches:
      - development
      
      
jobs:
  somejob:
    runs-on: ubuntu-latest
    timeout-minutes: 1


    steps:
      - name: Echo it worked
        run: echo "This workflow is running"
        
        
      - name: Checkout repository
        uses: actions/checkout@v2


