name: Pull Request Workflow
on:
  pull_request:
    types:
      - opened
      - reopened
      - ready_for_review
      - synchronize
    branches:
      - development

jobs:
  somejob:
    runs-on: ubuntu-latest
    timeout-minutes: 1

    steps:
      - name: Echo it worked
        run: echo "This workflow is running"

      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Check base branch
        run: |
          if [[ "${{ github.event.pull_request.base.ref }}" != "development" ]]; then
            echo "This workflow only runs on the 'development' branch."
            exit 0
          fi
